/**
 * generated by Xtext 2.10.0
 */
package be.unamur.iotdsl.xtext;

import be.unamur.iotdsl.xtext.AbstractIoTDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IoTDSLRuntimeModule extends AbstractIoTDSLRuntimeModule {
}
