/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep;

import org.xtext.example.cep.CepStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CepStandaloneSetup extends CepStandaloneSetupGenerated {
  public static void doSetup() {
    CepStandaloneSetup _cepStandaloneSetup = new CepStandaloneSetup();
    _cepStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
