/*
 * generated by Xtext
 */
package be.unamur.iotdevice;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IoTDeviceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return be.unamur.iotdevice.ui.internal.IoTDeviceActivator.getInstance().getInjector("be.unamur.iotdevice.IoTDevice");
	}

}
