/**
 * generated by Xtext 2.10.0
 */
package be.unamur.iotdsl.xtext.ui.contentassist;

import be.unamur.iotdsl.xtext.ui.contentassist.AbstractIoTDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class IoTDSLProposalProvider extends AbstractIoTDSLProposalProvider {
}
