/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.cep.ui.internal.CepActivator;

public class CepUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CepActivator.getInstance().getInjector("org.xtext.example.cep.Cep");
	}

}
