/*
 * generated by Xtext
 */
package be.unamur.iotdevice.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IoTDeviceUiModule extends be.unamur.iotdevice.ui.AbstractIoTDeviceUiModule {
	public IoTDeviceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
