/*
 * generated by Xtext 2.12.0
 */
package be.unamur.iot.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class IoTDSLProposalProvider extends AbstractIoTDSLProposalProvider {
}
