/*
 * generated by Xtext 2.10.0
 */
package be.unamur.iotdsl.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IoTDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("be/unamur/iotdsl/xtext/parser/antlr/internal/InternalIoTDSL.tokens");
	}
}
