/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep.cep;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cep.cep.ComplexEvent#getPattern <em>Pattern</em>}</li>
 *   <li>{@link org.xtext.example.cep.cep.ComplexEvent#getConditionExpression <em>Condition Expression</em>}</li>
 *   <li>{@link org.xtext.example.cep.cep.ComplexEvent#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cep.cep.ComplexEvent#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cep.cep.CepPackage#getComplexEvent()
 * @model
 * @generated
 */
public interface ComplexEvent extends Rule
{
  /**
   * Returns the value of the '<em><b>Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pattern</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' containment reference.
   * @see #setPattern(Expression)
   * @see org.xtext.example.cep.cep.CepPackage#getComplexEvent_Pattern()
   * @model containment="true"
   * @generated
   */
  Expression getPattern();

  /**
   * Sets the value of the '{@link org.xtext.example.cep.cep.ComplexEvent#getPattern <em>Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' containment reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(Expression value);

  /**
   * Returns the value of the '<em><b>Condition Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition Expression</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Expression</em>' attribute.
   * @see #setConditionExpression(String)
   * @see org.xtext.example.cep.cep.CepPackage#getComplexEvent_ConditionExpression()
   * @model
   * @generated
   */
  String getConditionExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.cep.cep.ComplexEvent#getConditionExpression <em>Condition Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Expression</em>' attribute.
   * @see #getConditionExpression()
   * @generated
   */
  void setConditionExpression(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.cep.cep.CepPackage#getComplexEvent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cep.cep.ComplexEvent#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cep.cep.CEParameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.example.cep.cep.CepPackage#getComplexEvent_Params()
   * @model containment="true"
   * @generated
   */
  EList<CEParameter> getParams();

} // ComplexEvent
