/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep.cep;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.cep.cep.CepPackage#getLiteralExpression()
 * @model
 * @generated
 */
public interface LiteralExpression extends Expression
{
} // LiteralExpression
