/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep.cep;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.cep.cep.CepPackage#getRealType()
 * @model
 * @generated
 */
public interface RealType extends PrimitiveType
{
} // RealType
