/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep.cep;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cep.cep.TypeReference#getPtype <em>Ptype</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cep.cep.CepPackage#getTypeReference()
 * @model
 * @generated
 */
public interface TypeReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Ptype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ptype</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ptype</em>' containment reference.
   * @see #setPtype(PrimitiveType)
   * @see org.xtext.example.cep.cep.CepPackage#getTypeReference_Ptype()
   * @model containment="true"
   * @generated
   */
  PrimitiveType getPtype();

  /**
   * Sets the value of the '{@link org.xtext.example.cep.cep.TypeReference#getPtype <em>Ptype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ptype</em>' containment reference.
   * @see #getPtype()
   * @generated
   */
  void setPtype(PrimitiveType value);

} // TypeReference
