/*
 * generated by Xtext 2.10.0
 */
package be.unamur.iotdsl.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIoTDSLScopeProvider extends DelegatingScopeProvider {
}
