/**
 * generated by Xtext
 */
package be.unamur.iotdevice.ui.contentassist;

import be.unamur.iotdevice.ui.contentassist.AbstractIoTDeviceProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class IoTDeviceProposalProvider extends AbstractIoTDeviceProposalProvider {
}
