/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep.cep.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.cep.cep.CEParameter;
import org.xtext.example.cep.cep.CepPackage;
import org.xtext.example.cep.cep.ComplexEvent;
import org.xtext.example.cep.cep.Expression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Complex Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cep.cep.impl.ComplexEventImpl#getPattern <em>Pattern</em>}</li>
 *   <li>{@link org.xtext.example.cep.cep.impl.ComplexEventImpl#getConditionExpression <em>Condition Expression</em>}</li>
 *   <li>{@link org.xtext.example.cep.cep.impl.ComplexEventImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cep.cep.impl.ComplexEventImpl#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComplexEventImpl extends RuleImpl implements ComplexEvent
{
  /**
   * The cached value of the '{@link #getPattern() <em>Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPattern()
   * @generated
   * @ordered
   */
  protected Expression pattern;

  /**
   * The default value of the '{@link #getConditionExpression() <em>Condition Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionExpression()
   * @generated
   * @ordered
   */
  protected static final String CONDITION_EXPRESSION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConditionExpression() <em>Condition Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionExpression()
   * @generated
   * @ordered
   */
  protected String conditionExpression = CONDITION_EXPRESSION_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected EList<CEParameter> params;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComplexEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CepPackage.Literals.COMPLEX_EVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getPattern()
  {
    return pattern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPattern(Expression newPattern, NotificationChain msgs)
  {
    Expression oldPattern = pattern;
    pattern = newPattern;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CepPackage.COMPLEX_EVENT__PATTERN, oldPattern, newPattern);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPattern(Expression newPattern)
  {
    if (newPattern != pattern)
    {
      NotificationChain msgs = null;
      if (pattern != null)
        msgs = ((InternalEObject)pattern).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CepPackage.COMPLEX_EVENT__PATTERN, null, msgs);
      if (newPattern != null)
        msgs = ((InternalEObject)newPattern).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CepPackage.COMPLEX_EVENT__PATTERN, null, msgs);
      msgs = basicSetPattern(newPattern, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CepPackage.COMPLEX_EVENT__PATTERN, newPattern, newPattern));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getConditionExpression()
  {
    return conditionExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConditionExpression(String newConditionExpression)
  {
    String oldConditionExpression = conditionExpression;
    conditionExpression = newConditionExpression;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CepPackage.COMPLEX_EVENT__CONDITION_EXPRESSION, oldConditionExpression, conditionExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CepPackage.COMPLEX_EVENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<CEParameter> getParams()
  {
    if (params == null)
    {
      params = new EObjectContainmentEList<CEParameter>(CEParameter.class, this, CepPackage.COMPLEX_EVENT__PARAMS);
    }
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CepPackage.COMPLEX_EVENT__PATTERN:
        return basicSetPattern(null, msgs);
      case CepPackage.COMPLEX_EVENT__PARAMS:
        return ((InternalEList<?>)getParams()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CepPackage.COMPLEX_EVENT__PATTERN:
        return getPattern();
      case CepPackage.COMPLEX_EVENT__CONDITION_EXPRESSION:
        return getConditionExpression();
      case CepPackage.COMPLEX_EVENT__NAME:
        return getName();
      case CepPackage.COMPLEX_EVENT__PARAMS:
        return getParams();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CepPackage.COMPLEX_EVENT__PATTERN:
        setPattern((Expression)newValue);
        return;
      case CepPackage.COMPLEX_EVENT__CONDITION_EXPRESSION:
        setConditionExpression((String)newValue);
        return;
      case CepPackage.COMPLEX_EVENT__NAME:
        setName((String)newValue);
        return;
      case CepPackage.COMPLEX_EVENT__PARAMS:
        getParams().clear();
        getParams().addAll((Collection<? extends CEParameter>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CepPackage.COMPLEX_EVENT__PATTERN:
        setPattern((Expression)null);
        return;
      case CepPackage.COMPLEX_EVENT__CONDITION_EXPRESSION:
        setConditionExpression(CONDITION_EXPRESSION_EDEFAULT);
        return;
      case CepPackage.COMPLEX_EVENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CepPackage.COMPLEX_EVENT__PARAMS:
        getParams().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CepPackage.COMPLEX_EVENT__PATTERN:
        return pattern != null;
      case CepPackage.COMPLEX_EVENT__CONDITION_EXPRESSION:
        return CONDITION_EXPRESSION_EDEFAULT == null ? conditionExpression != null : !CONDITION_EXPRESSION_EDEFAULT.equals(conditionExpression);
      case CepPackage.COMPLEX_EVENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CepPackage.COMPLEX_EVENT__PARAMS:
        return params != null && !params.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (conditionExpression: ");
    result.append(conditionExpression);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ComplexEventImpl
