/*
 * generated by Xtext 2.12.0
 */
package be.unamur.iot

import org.eclipse.xtext.naming.IQualifiedNameProvider
import be.unamur.iot.naming.IotDSLQualifiedNameProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IoTDSLRuntimeModule extends AbstractIoTDSLRuntimeModule {
	
	override Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return IotDSLQualifiedNameProvider;
	}
	
}
