/*
 * generated by Xtext 2.12.0
 */
package be.unamur.iot


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IoTDSLStandaloneSetup extends IoTDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new IoTDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
