/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.cep.ui.AbstractCepUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CepUiModule extends AbstractCepUiModule {
  public CepUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
