/*
 * generated by Xtext 2.12.0
 */
package be.unamur.iot.ide

import be.unamur.iot.IotDslRuntimeModule
import be.unamur.iot.IotDslStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class IotDslIdeSetup extends IotDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new IotDslRuntimeModule, new IotDslIdeModule))
	}
	
}
