/*
 * generated by Xtext 2.10.0
 */
package be.unamur.iotdsl.xtext.ui.tests;

import be.unamur.iotdsl.xtext.ui.internal.XtextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class IoTDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("be.unamur.iotdsl.xtext.IoTDSL");
	}

}
