/*
 * generated by Xtext
 */
package be.unamur.iotdevice;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IoTDeviceStandaloneSetup extends IoTDeviceStandaloneSetupGenerated{

	public static void doSetup() {
		new IoTDeviceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

