/*
 * generated by Xtext
 */
package be.unamur.iotdevice;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IoTDeviceRuntimeModule extends be.unamur.iotdevice.AbstractIoTDeviceRuntimeModule {

}
