/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.cep.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.cep.parser.antlr.internal.InternalCepParser;
import org.xtext.example.cep.services.CepGrammarAccess;

public class CepParser extends AbstractAntlrParser {

	@Inject
	private CepGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCepParser createParser(XtextTokenStream stream) {
		return new InternalCepParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CepGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CepGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
