/*
 * generated by Xtext 2.10.0
 */
package be.unamur.iotdsl.xtext.ui;

import be.unamur.iotdsl.xtext.ui.internal.XtextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IoTDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtextActivator.getInstance().getInjector(XtextActivator.BE_UNAMUR_IOTDSL_XTEXT_IOTDSL);
	}
	
}
